typedef struct nrf_library NrfLibrary, * NrfLibrary_ptr;
typedef struct nrf_io_interface NrfIoInterface, * NrfIoInterface_ptr;
typedef struct nrf_io_callbacks NrfIoCallbacks, * NrfIoCallbacks_ptr;
typedef struct nrf_registers NrfRegisters, * NrfIoRegisters_ptr;
typedef struct nrf_spi_device NrfSpiDevice, * NrfSpiDevice_ptr;
typedef struct nrf_reg_status NrfReg_STATUS, * NrfReg_STATUS_ptr;
typedef struct nrf_reg_config NrfReg_CONFIG, * NrfReg_CONFIG_ptr;
typedef struct nrf_reg_EN_AA NrfReg_EN_AA, * NrfReg_EN_AA_ptr;
typedef struct nrf_reg_EN_RXADDR NrfReg_EN_RXADDR, * NrfReg_EN_RXADDR_ptr;